---
- name: Create Development directory
  file:
    path: "{{ ansible_user_dir }}/Development"
    state: directory


- name: Development symlinks to Dropbox
  file:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    state: link
  with_items: "{{ dev_symlinks }}"
